import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import ArticlePreview from '../components/home/ArticlePreview';
import { getBlogPosts } from '../lib/blog';
import { motion } from "framer-motion"

export default function Home({ blogPosts }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <motion.h1 layoutId="title">My Website</motion.h1>

        {
          blogPosts.map(post => {
            return (
              <ArticlePreview data={post}/>
            )
          })
        }
      </main>

      <div>
      </div>
    </div>
  )
}

export async function getStaticProps(context) {
  const blogPosts = getBlogPosts();

  return {
    props: {
      blogPosts
    }
  }
}